export const APP_NAME = "ToolInsta";

export const messages = {
  en: {
    input_placeholder_text: "Paste Instagram URL",
    top_heading: "Downloader for Instagram",
    top_subheading: "Download Instagram Video, Reels, Photo and Story",
    video_heading: "Instagram Video Downloader",
    video_subheading: "Download Instagram Videos by pasting the Url directly",
    reel_heading: "Instagram Reels Downloader",
    reel_subheading: "Download Instagram Reels by pasting the Url directly",
    story_heading: "Instagram Stories Downloader",
    story_subheading: "Download Instagram Stories by pasting the Url directly",
    photo_heading: "Instagram Photos Downloader",
    photo_subheading: "Download Instagram Photos by pasting the Url directly",
    igtv_heading: "Instagram IGTV Downloader",
    igtv_subheading:
      "Download Instagram IGTV videos by pasting the Url directly",
    home_desc_heading: ["Instagram Video, Reels, Photo, Story Download"],
    home_desc_content: [
      "Download instagram post easily with ToolInsta. No login required. Just paste the link and download. Free and fast. ToolInsta is Best instagram post downloader for instagram post download online or insta postdownload.",
    ],
    video_desc_heading: ["Instagram Video Download "],
    video_desc_content: [
      "Download instagram video easily with ToolInsta. No login required. Just paste the link and download. Free and fast. ToolInsta is Best instagram video downloader for instagram video download online or download for insta video.",
    ],
    photo_desc_heading: ["Instagram Photo Download"],
    photo_desc_content: [
      "Download instagram photo easily with ToolInsta. No login required. Just paste the link and download. Free and fast. ToolInsta is Best instagram photo downloader for instagram photo download online or insta photo download hd, 4k.",
    ],
    reel_desc_heading: ["Instagram Reels Download"],
    reel_desc_content: [
      "Download instagram Reels easily with ToolInsta. No login required. Just paste the link and download. Free and fast. ToolInsta is Best instagram reels downloader for instagram reels video download online or insta reels download video hd.",
    ],
    story_desc_heading: ["Instagram Story Download"],
    story_desc_content: [
      "Download instagram Story easily with ToolInsta. No login required. Just paste the link and download. Free and fast. ToolInsta is Best instagram stories downloader for instagram story download online or download story ig with Instagram story saver.",
    ],
    igtv_desc_heading: ["Instagram IGTV Video Download"],
    igtv_desc_content: [
      "Download instagram igtv video easily with ToolInsta. No login required. Just paste the link and download. Free and fast. ToolInsta is Best instagram igtv video downloader for instagram igtv video download online.",
    ],
    about_heading: [
      "Downloader for Instagram : Download Instagram Video, Reels, Photo and Story",
    ],
    about_content: [
      "Toolinsta is an online tool or software that allows users to download Videos, Photos, Stories, Reels and IGTV from Instagram in few simple steps. Toolinsta Instagram video downloader website, where you can download your favorite Instagram videos easily and quickly. Our website is user-friendly, and you don't need to have any technical knowledge to use it.",
      "Toolinsta is designed to be easy to use on any device (PC, Mac, Android, iOS) without installing supporting software. Download high quality Instagram content (download Instagram videos in mp4 format, download Reels videos, download IGTV videos, download Photo, Download Story). To download an Instagram video, simply copy the video link from Instagram and paste it into our downloader. Then click the download button, and your video will start downloading in no time.",
      "Our website is free to use, and you can download as many videos, photos, stories as you want. We also take your privacy seriously, and we don't store any of your personal information or the videos you download. We guarantee a safe and secure experience for all our users.",
    ],
    about_video_heading: [
      "Instagram To Video Download",
      "Instagram Video Downloader",
      "Instagram Video Downloader iphone",
      "Save videos From Instagram",
    ],
    about_video_content: [
      "We get many such videos in Instagram, which we want to download. But there is no option of direct video download in Instagram. That's why we need another third party site. Our tool is the best downloader for downloading Instagram videos.  It's simple, it's easy, and it has no limits of the video downloading number. One click to download instagram video.",
      "An Instagram video downloader website is a platform that allows users to download videos from Instagram onto their devices. Users can simply copy the URL of the Instagram video they wish to download and paste it into the website's download box and Hits download button. Instagram Video automatically start to downloading. ToolInsta is created to download Instagram videos for any purpose you want.  it's a quick and easy way to get your Instagram content downloaded offline to your device. To use an Instagram Video downloader online, you typically need to provide the link to the Instagram post that you want to download. ",
      'There are several ways to download Instagram videos on an iPhone, including using a third-party app or a web-based service. ToolInsta offers a free web-based tool which allows you to download Instagram videos online, its a quick and easy way to get your Instagram content downloaded offline to your device. Here are the steps to download Instagram videos on an iPhone using a web-based service: Open the Instagram app select "Copy Link". Then Open Safari or any web browser on your iPhone and go to a web-based Instagram video downloader website, such as ToolInsta. Paste the copied link into the download box on the website and click "Download".',
      "Saving videos on Instagram is very easy. Open the Instagram app and click on the profile photo in the profile section. From the Instagram feed, click on the video you want to save in the phone's camera roll. Click on the three dots at the bottom of the video and click on “Save to Camera Roll” from the pop-up menu. The video will get saved in the camera roll. It is important to note that downloading Instagram videos without the owner's permission is a violation of Instagram's terms of service, and you should use any downloaded content for personal use only.",
    ],
    about_reel_heading: [
      "Instagram To Reels Download",
      "Instagram Reels Downloader",
      "Instagram Reels Downloader iphone",
      "Save Reels From Instagram",
    ],
    about_reel_content: [
      "We get many such Reels in Instagram, which we want to download. But there is no option of direct Reels download in Instagram. That's why we need another third party site. Our tool is the best downloader for downloading Instagram Reels.  It's simple, it's easy, and it has no limits of the video downloading number. One click to download instagram video.",
      "An Instagram Reels downloader website is a platform that allows users to download videos from Instagram onto their devices. Users can simply copy the URL of the Instagram reels they wish to download and paste it into the website's download box and Hits download button. Instagram Video automatically start to downloading. ToolInsta is created to download Instagram Reels for any purpose you want.  it's a quick and easy way to get your Instagram content downloaded offline to your device. To use an Instagram Video downloader online, you typically need to provide the link to the Instagram post that you want to download. ",
      'There are several ways to download Instagram Reels on an iPhone, including using a third-party app or a web-based service. ToolInsta offers a free web-based tool which allows you to download Instagram reels online, it is a quick and easy way to get your Instagram content downloaded offline to your device. Here are the steps to download Instagram videos on an iPhone using a web-based service: Open the Instagram app select "Copy Link". Then Open Safari or any web browser on your iPhone and go to a web-based Instagram video downloader website, such as ToolInsta. Paste the copied link into the download box on the website and click "Download".',
      "Saving Reels on Instagram is very easy. Open the Instagram app and click on the profile photo in the profile section. From the Instagram feed, click on the reels you want to save in the phone's camera roll. Click on the three dots at the bottom of the video and click on “Save to Camera Roll” from the pop-up menu. The video will get saved in the camera roll. It is important to note that downloading Instagram videos without the owner's permission is a violation of Instagram's terms of service, and you should use any downloaded content for personal use only.",
    ],
    about_story_heading: [
      "Instagram To Story Download",
      "Instagram Story Downloader",
      "Instagram Story Downloader iphone",
      "Save Story From Instagram",
    ],
    about_story_content: [
      "We get many such photos in Instagram, which we want to download. But there is no option of direct Reels download in Instagram. That's why we need another third party site. Our tool is the best downloader for downloading Instagram stories.  It's simple, it's easy, and it has no limits of the video downloading number. One click to download instagram video.",
      "An Instagram photos downloader website is a platform that allows users to download videos from Instagram onto their devices. Users can simply copy the URL of the Instagram stories they wish to download and paste it into the website's download box and Hits download button. Instagram Video automatically start to downloading. ToolInsta is created to download Instagram Reels for any purpose you want.  it's a quick and easy way to get your Instagram content downloaded offline to your device. To use an Instagram Video downloader online, you typically need to provide the link to the Instagram post that you want to download. ",
      'There are several ways to download Instagram stories on an iPhone, including using a third-party app or a web-based service. ToolInsta offers a free web-based tool which allows you to download Instagram stories online, it is a quick and easy way to get your Instagram content downloaded offline to your device. Here are the steps to download Instagram videos on an iPhone using a web-based service: Open the Instagram app select "Copy Link". Then Open Safari or any web browser on your iPhone and go to a web-based Instagram video downloader website, such as ToolInsta. Paste the copied link into the download box on the website and click "Download".',
      "Saving photos on Instagram is very easy. Open the Instagram app and click on the profile photo in the profile section. From the Instagram feed, click on the stories you want to save in the phone's camera roll. Click on the three dots at the bottom of the video and click on “Save to Camera Roll” from the pop-up menu. The video will get saved in the camera roll. It is important to note that downloading Instagram videos without the owner's permission is a violation of Instagram's terms of service, and you should use any downloaded content for personal use only.",
    ],
    about_photo_heading: [
      "Instagram To Photo Download",
      "Instagram Photo Downloader",
      "Instagram Photo Downloader iphone",
      "Save Photo From Instagram",
    ],
    about_photo_content: [
      "We get many such igtv in Instagram, which we want to download. But there is no option of direct Reels download in Instagram. That's why we need another third party site. Our tool is the best downloader for downloading Instagram stories.  It's simple, it's easy, and it has no limits of the video downloading number. One click to download instagram video.",
      "An Instagram igtv downloader website is a platform that allows users to download videos from Instagram onto their devices. Users can simply copy the URL of the Instagram stories they wish to download and paste it into the website's download box and Hits download button. Instagram Video automatically start to downloading. ToolInsta is created to download Instagram Reels for any purpose you want.  it's a quick and easy way to get your Instagram content downloaded offline to your device. To use an Instagram Video downloader online, you typically need to provide the link to the Instagram post that you want to download. ",
      'There are several ways to download Instagram igtv on an iPhone, including using a third-party app or a web-based service. ToolInsta offers a free web-based tool which allows you to download Instagram stories online, it is a quick and easy way to get your Instagram content downloaded offline to your device. Here are the steps to download Instagram videos on an iPhone using a web-based service: Open the Instagram app select "Copy Link". Then Open Safari or any web browser on your iPhone and go to a web-based Instagram video downloader website, such as ToolInsta. Paste the copied link into the download box on the website and click "Download".',
      "Saving photos on Instagram is very easy. Open the Instagram app and click on the profile photo in the profile section. From the Instagram feed, click on the stories you want to save in the phone's camera roll. Click on the three dots at the bottom of the video and click on “Save to Camera Roll” from the pop-up menu. The video will get saved in the camera roll. It is important to note that downloading Instagram videos without the owner's permission is a violation of Instagram's terms of service, and you should use any downloaded content for personal use only.",
    ],
    about_igtv_heading: [
      "Instagram To IGTV Download",
      "Instagram IGTV Downloader",
      "Instagram IGTV Downloader iphone",
      "Save IGTV From Instagram",
    ],
    about_igtv_content: [
      "We get many such stories in Instagram, which we want to download. But there is no option of direct Reels download in Instagram. That's why we need another third party site. Our tool is the best downloader for downloading Instagram stories.  It's simple, it's easy, and it has no limits of the video downloading number. One click to download instagram video.",
      "An Instagram stories downloader website is a platform that allows users to download videos from Instagram onto their devices. Users can simply copy the URL of the Instagram stories they wish to download and paste it into the website's download box and Hits download button. Instagram Video automatically start to downloading. ToolInsta is created to download Instagram Reels for any purpose you want.  it's a quick and easy way to get your Instagram content downloaded offline to your device. To use an Instagram Video downloader online, you typically need to provide the link to the Instagram post that you want to download. ",
      'There are several ways to download Instagram stories on an iPhone, including using a third-party app or a web-based service. ToolInsta offers a free web-based tool which allows you to download Instagram stories online, it is a quick and easy way to get your Instagram content downloaded offline to your device. Here are the steps to download Instagram videos on an iPhone using a web-based service: Open the Instagram app select "Copy Link". Then Open Safari or any web browser on your iPhone and go to a web-based Instagram video downloader website, such as ToolInsta. Paste the copied link into the download box on the website and click "Download".',
      "Saving stories on Instagram is very easy. Open the Instagram app and click on the profile photo in the profile section. From the Instagram feed, click on the stories you want to save in the phone's camera roll. Click on the three dots at the bottom of the video and click on “Save to Camera Roll” from the pop-up menu. The video will get saved in the camera roll. It is important to note that downloading Instagram videos without the owner's permission is a violation of Instagram's terms of service, and you should use any downloaded content for personal use only.",
    ],
    why_toolinsta_heading: [
      "Why should you use ToolInsta - Instagram Downloader?",
    ],
    why_toolinsta_content: [
      "What is Instagram : Instagram is a popular social media platform that allows users to share photos, videos, reels and story with their followers. Instagram has become one of the most widely used social media platforms in the world, with over 1 billion active monthly users.",
      "Every day, millions of new photos, videos, reels are posted on Instagram, but Instagram does not allow users to download and store photos and videos to your device. Only Users can follow other users, like and comment on their posts, and also use hashtags to discover new content. The best way to get Instagram content is through third-party sites like ToolInsta downloader.",
    ],
    features_heading: ["Features of ToolInsta"],
    features_content: [
      "Video download Instagram",
      "ToolInsta that allows users to download videos from Instagram. Users can copy and paste the Instagram URL of the video they wish to download into the website's download field. The website then extracts the video and provides a download link for the user to save it to their device.",
      "Instagram photo downloader",
      "Instagram photo downloader service provided by ToolInsta. Toolinsta makes it easy to download and save Instagram images easily. You can also download a single post image as well as download multiple Instagram photos.",
      "Download Instagram Reels",
      "ToolInsta best downloader for download instagram reel video in mp4 format on all devices (PC, Mac, Android, iOS).",
      "Download IGTV Video",
      "IGTV is a long video on Instagram, ToolInsta supports download IGTV videos to your device for storage or playback when there is offline. Our Instagram IGTV downloader can help you to save your favorite videos.",
      "Instagram Story Download",
      "Toolinsta Instagram Story download tool allows users to download content from Instagram stories quickly.  Instagram Story is a combination of photos and videos, creating a story that users want to share with the world. Sometimes you want to archive a story you like but the feature is not supported in the app. Snapinsta was created to solve that problem.",
      "Instagram Audio Download",
      "Instagram Audio Download refers to the process of downloading audio files from Instagram. These audio files can be in the form of music, sound effects, or any other audio content that has been uploaded on Instagram. if you're looking for some quality music then you should give this Toolinsta audio download tool a try. You may already know that Instagram reels have duets and remix options which creates some fantastic music that seems out of this world because it isn't available on any other platform.",
    ],
    how_to_download_heading: ["HOW TO DOWNLOAD VIDEOS FROM INSTAGRAM?"],
    how_to_download_content: [
      "To download photos or videos from Instagram, You must follow these three easy steps.",
      "Step 1:",
      "Open the Instagram application or website, and login to your account. After login copy the URL of the photo, video, reels, carousel, story or IGTV.",
      "Step 2:",
      "Go to the website ToolInsta, paste the Instagram link you just copied into input box and press the Download button.",
      "Step 3:",
      "Choose the quality of the video, after that the download will start.",
    ],
    how_to_download_video_heading: ["HOW TO DOWNLOAD VIDEOS FROM INSTAGRAM?"],
    how_to_download_video_content: [
      "To download photos or videos from Instagram, You must follow these three easy steps.",
      "Step 1:",
      "Open the Instagram application or website, and login to your account. After login copy the URL of the video.",
      "Step 2:",
      "Go to the website ToolInsta, paste the Instagram link you just copied into input box and press the Download button.",
      "Step 3:",
      "Choose the quality of the video, after that the download will start.",
    ],
    how_to_download_reel_heading: ["HOW TO DOWNLOAD REELS FROM INSTAGRAM?"],
    how_to_download_reel_content: [
      "To download photos or videos from Instagram, You must follow these three easy steps.",
      "Step 1:",
      "Open the Instagram application or website, and login to your account. After login copy the URL of the reel.",
      "Step 2:",
      "Go to the website ToolInsta, paste the Instagram link you just copied into input box and press the Download button.",
      "Step 3:",
      "Choose the quality of the video, after that the download will start.",
    ],
    how_to_download_photo_heading: ["HOW TO DOWNLOAD PHOTOS FROM INSTAGRAM?"],
    how_to_download_photo_content: [
      "To download photos from Instagram, You must follow these three easy steps.",
      "Step 1:",
      "Open the Instagram application or website, and login to your account. After login copy the URL of the reel.",
      "Step 2:",
      "Go to the website ToolInsta, paste the Instagram link you just copied into input box and press the Download button.",
      "Step 3:",
      "Choose the quality of the video, after that the download will start.",
    ],
    how_to_download_igtv_heading: [
      "HOW TO DOWNLOAD IGTV VIDEOS FROM INSTAGRAM?",
    ],
    how_to_download_igtv_content: [
      "To download igtv videos from Instagram, You must follow these three easy steps.",
      "Step 1:",
      "Open the Instagram application or website, and login to your account. After login copy the URL of the reel.",
      "Step 2:",
      "Go to the website ToolInsta, paste the Instagram link you just copied into input box and press the Download button.",
      "Step 3:",
      "Choose the quality of the video, after that the download will start.",
    ],
    how_to_download_story_heading: ["HOW TO DOWNLOAD STORIES FROM INSTAGRAM?"],
    how_to_download_story_content: [
      "To download photos or videos from Instagram, You must follow these three easy steps.",
      "Step 1:",
      "Open the Instagram application or website, and login to your account. After login copy the URL of the story.",
      "Step 2:",
      "Go to the website ToolInsta, paste the Instagram link you just copied into input box and press the Download button.",
      "Step 3:",
      "Choose the quality of the video, after that the download will start.",
    ],
    why_choose_tootlinsta_heading: [
      "Why Choose ToolInsta for BEST TOOL INSTAGRAM DOWNLOADER",
    ],
    why_choose_tootlinsta_content: [
      "Toolinsta is the best Instagram downloader third party website.",
      "User-Friendly Interface",
      "A good Instagram downloader should have a user-friendly interface that is easy to navigate. It should be easy to understand and operate even for beginners. That's why our website has been built keeping the user in mind.",
      "Download Speed",
      "The website is able to download your desired content from Instagram quickly, and it should not take too much time.You can download the fastest in our website.",
      "Safety",
      "The website is safe and secure, with no risk of viruses or malware. You can feel confident that your device will not be compromised by using the website. Our site No need to login to your Instagram account.",
    ],
    faq_heading: ["FAQ"],
    faq_content: [
      "What is Instagram Downloader?",
      "An Instagram downloader is a tool that allows you to download photos, videos, reels, story and other content from Instagram onto your computer or mobile device. In case you need to use it later offline. ToolInsta is the best tool for downloading from Instagram.",
      "Can I save videos directly on Instagram?",
      "Yes, you can save videos directly on Instagram, but only if the video is from your own account. You will need a third-party site to download videos from other's accounts.",
      "How to download videos and photos on Instagram?",
      "Go to an Instagram downloader website like ToolInsta,  Then paste the Instagram post url into the input box and press the Download button.",
      "How to download Instagram photos and videos on Android phone?",
      "Download any third-party Instagram downloader app and goto your Instagram account. Paste the copied Instagram link into the input box and hit download button.",
      "Are there any limits on the number of videos I can download?",
      "There is no limit. You can download as many as you want.",
      "Can I download Instagram Story?",
      "Yes you can download. For this, go to the toolinsta site and paste the link of the story and download it.",
      "Do I have to pay for this Download Instagram Video & Photo service?",
      "Toolinsta service is completely free and has no download limits.",
      "Where are Instagram videos and photos saved after downloading?",
      'Please check the "Downloads" folder in your phone or the "download history" section of your browser.',
      "What is the highest quality of images and videos I can download?",
      "The quality of photos and videos depends on the original uploaded image. Still, usually, the highest image resolution is 1080x1350 pixels, which is the limit of Instagram. As for the video, it is HD (720p) in most cases.",
    ],
  },
  es: {
    input_placeholder_text: "Pegar URL de Instagram",
    top_heading: "Descargador de Instagram",
    top_subheading:
      "Descargue videos, carretes, fotos e historias de Instagram",
    video_heading: "Descargador de videos de Instagram",
    video_subheading:
      "Descargue videos de Instagram pegando la URL directamente",
    reel_heading: "Descargador de carretes de Instagram",
    reel_subheading: "Descarga Instagram Reels pegando la URL directamente",
    story_heading: "Descargador de historias de Instagram",
    story_subheading: "Descarga Instagram Stories pegando la URL directamente",
    photo_heading: "Descargador de fotos de Instagram",
    photo_subheading: "Descarga Fotos de Instagram pegando la URL directamente",
    igtv_heading: "Descargador de Instagram IGTV",
    igtv_subheading:
      "Descargue videos de Instagram IGTV pegando la URL directamente",
    home_desc_heading: [
      "Video de Instagram, carretes, fotos, descarga de historias",
    ],
    home_desc_content: [
      "Descargue la publicación de Instagram fácilmente con ToolInsta. ",
    ],
    video_desc_heading: ["Descarga de videos de Instagram "],
    video_desc_content: [
      "Descargue videos de Instagram fácilmente con ToolInsta. ",
    ],
    photo_desc_heading: ["Descarga de fotos de Instagram"],
    photo_desc_content: [
      "Descarga fotos de Instagram fácilmente con ToolInsta. ",
    ],
    reel_desc_heading: ["Descargar carretes de Instagram"],
    reel_desc_content: ["Descarga Instagram Reels fácilmente con ToolInsta. "],
    story_desc_heading: ["Descarga de la historia de Instagram"],
    story_desc_content: ["Descarga Instagram Story fácilmente con ToolInsta. "],
    igtv_desc_heading: ["Descarga de videos de Instagram IGTV"],
    igtv_desc_content: [
      "Descargue videos de Instagram igtv fácilmente con ToolInsta. ",
    ],
    about_heading: [
      "Descargador para Instagram: descargue videos, carretes, fotos e historias de Instagram",
    ],
    about_content: [
      "Toolinsta es una herramienta o software en línea que permite a los usuarios descargar videos, fotos, historias, carretes e IGTV de Instagram en unos simples pasos. ",
      "Toolinsta está diseñado para ser fácil de usar en cualquier dispositivo (PC, Mac, Android, iOS) sin instalar software de soporte. ",
      "Nuestro sitio web es de uso gratuito y puede descargar tantos videos, fotos e historias como desee. ",
    ],
    about_video_heading: [
      "Descarga de Instagram a video",
      "Descargador de videos de Instagram",
      "Descargador de videos de Instagram para iPhone",
      "Guardar videos de Instagram",
    ],
    about_video_content: [
      "Recibimos muchos videos de este tipo en Instagram, que queremos descargar. ",
      "Un sitio web de descarga de videos de Instagram es una plataforma que permite a los usuarios descargar videos de Instagram en sus dispositivos.  ",
      "Hay varias formas de descargar videos de Instagram en un iPhone, incluido el uso de una aplicación de terceros o un servicio basado en la web. ",
      "Guardar videos en Instagram es muy fácil. ",
    ],
    about_reel_heading: [
      "Descarga de Instagram a carretes",
      "Descargador de carretes de Instagram",
      "Descargador de carretes de Instagram para iPhone",
      "Guardar carretes de Instagram",
    ],
    about_reel_content: [
      "Obtenemos muchos Reels de este tipo en Instagram, que queremos descargar. ",
      "Un sitio web de descarga de Instagram Reels es una plataforma que permite a los usuarios descargar videos de Instagram en sus dispositivos.  ",
      "Hay varias formas de descargar Instagram Reels en un iPhone, incluido el uso de una aplicación de terceros o un servicio basado en la web. ",
      "Guardar Reels en Instagram es muy fácil. ",
    ],
    about_story_heading: [
      "Descarga de Instagram a historia",
      "Descargador de historias de Instagram",
      "Descargador de historias de Instagram para iPhone",
      "Guardar historia de Instagram",
    ],
    about_story_content: [
      "Recibimos muchas fotos de este tipo en Instagram, que queremos descargar. ",
      "Un sitio web de descarga de fotos de Instagram es una plataforma que permite a los usuarios descargar videos de Instagram en sus dispositivos.  ",
      "Hay varias formas de descargar las historias de Instagram en un iPhone, incluido el uso de una aplicación de terceros o un servicio basado en la web. ",
      "Guardar fotos en Instagram es muy fácil. ",
    ],
    about_photo_heading: [
      "Instagram para descargar fotos",
      "Descargador de fotos de Instagram",
      "Descargador de fotos de Instagram para iPhone",
      "Guardar foto de Instagram",
    ],
    about_photo_content: [
      "Recibimos muchos de estos igtv en Instagram, que queremos descargar. ",
      "Un sitio web de descarga de Instagram igtv es una plataforma que permite a los usuarios descargar videos de Instagram en sus dispositivos.  ",
      "Hay varias formas de descargar Instagram igtv en un iPhone, incluido el uso de una aplicación de terceros o un servicio basado en la web. ",
      "Guardar fotos en Instagram es muy fácil. ",
    ],
    about_igtv_heading: [
      "Descarga de Instagram a IGTV",
      "Descargador de Instagram IGTV",
      "Descargador de Instagram IGTV iPhone",
      "Guardar IGTV de Instagram",
    ],
    about_igtv_content: [
      "Recibimos muchas historias de este tipo en Instagram, que queremos descargar. ",
      "Un sitio web de descarga de historias de Instagram es una plataforma que permite a los usuarios descargar videos de Instagram en sus dispositivos.  ",
      "Hay varias formas de descargar las historias de Instagram en un iPhone, incluido el uso de una aplicación de terceros o un servicio basado en la web. ",
      "Guardar historias en Instagram es muy fácil. ",
    ],
    why_toolinsta_heading: [
      "¿Por qué debería usar ToolInsta - Descargador de Instagram?",
    ],
    why_toolinsta_content: [
      "Qué es Instagram: Instagram es una popular plataforma de redes sociales que permite a los usuarios compartir fotos, videos, carretes e historias con sus seguidores. ",
      "Todos los días, se publican millones de fotos, videos y carretes nuevos en Instagram, pero Instagram no permite que los usuarios descarguen y almacenen fotos y videos en su dispositivo. ",
    ],
    features_heading: ["Características de ToolInsta"],
    features_content: [
      "Descarga de videos Instagram",
      "ToolInsta que permite a los usuarios descargar videos de Instagram. ",
      "Descargador de fotos de Instagram",
      "Servicio de descarga de fotos de Instagram proporcionado por ToolInsta. ",
      "Descargar carretes de Instagram",
      "ToolInsta, el mejor descargador para descargar videos de Instagram Reel en formato mp4 en todos los dispositivos (PC, Mac, Android, iOS).",
      "Descargar vídeo de IGTV",
      "IGTV es un video largo en Instagram, ToolInsta admite la descarga de videos IGTV a su dispositivo para almacenarlos o reproducirlos cuando no esté conectado. ",
      "Descarga de la historia de Instagram",
      "La herramienta de descarga Toolinsta Instagram Story permite a los usuarios descargar contenido de las historias de Instagram rápidamente. ",
      "Descarga de audio de Instagram",
      "Instagram Audio Download se refiere al proceso de descargar archivos de audio de Instagram. ",
    ],
    how_to_download_heading: ["¿CÓMO DESCARGAR VIDEOS DE INSTAGRAM?"],
    how_to_download_content: [
      "Para descargar fotos o videos de Instagram, debes seguir estos tres sencillos pasos.",
      "Paso 1:",
      "Abra la aplicación o el sitio web de Instagram e inicie sesión en su cuenta. ",
      "Paso 2:",
      "Vaya al sitio web ToolInsta, pegue el enlace de Instagram que acaba de copiar en el cuadro de entrada y presione el botón Descargar.",
      "Paso 3:",
      "Elija la calidad del video, luego comenzará la descarga.",
    ],
    how_to_download_video_heading: ["¿CÓMO DESCARGAR VIDEOS DE INSTAGRAM?"],
    how_to_download_video_content: [
      "Para descargar fotos o videos de Instagram, debes seguir estos tres sencillos pasos.",
      "Paso 1:",
      "Abra la aplicación o el sitio web de Instagram e inicie sesión en su cuenta. ",
      "Paso 2:",
      "Vaya al sitio web ToolInsta, pegue el enlace de Instagram que acaba de copiar en el cuadro de entrada y presione el botón Descargar.",
      "Paso 3:",
      "Elija la calidad del video, luego comenzará la descarga.",
    ],
    how_to_download_reel_heading: ["¿CÓMO DESCARGAR REELS DE INSTAGRAM?"],
    how_to_download_reel_content: [
      "Para descargar fotos o videos de Instagram, debes seguir estos tres sencillos pasos.",
      "Paso 1:",
      "Abra la aplicación o el sitio web de Instagram e inicie sesión en su cuenta. ",
      "Paso 2:",
      "Vaya al sitio web ToolInsta, pegue el enlace de Instagram que acaba de copiar en el cuadro de entrada y presione el botón Descargar.",
      "Paso 3:",
      "Elija la calidad del video, luego comenzará la descarga.",
    ],
    how_to_download_photo_heading: ["¿CÓMO DESCARGAR FOTOS DE INSTAGRAM?"],
    how_to_download_photo_content: [
      "Para descargar fotos de Instagram, debes seguir estos tres sencillos pasos.",
      "Paso 1:",
      "Abra la aplicación o el sitio web de Instagram e inicie sesión en su cuenta. ",
      "Paso 2:",
      "Vaya al sitio web ToolInsta, pegue el enlace de Instagram que acaba de copiar en el cuadro de entrada y presione el botón Descargar.",
      "Paso 3:",
      "Elija la calidad del video, luego comenzará la descarga.",
    ],
    how_to_download_igtv_heading: [
      "¿CÓMO DESCARGAR VIDEOS DE IGTV DESDE INSTAGRAM?",
    ],
    how_to_download_igtv_content: [
      "Para descargar videos igtv de Instagram, debes seguir estos tres sencillos pasos.",
      "Paso 1:",
      "Abra la aplicación o el sitio web de Instagram e inicie sesión en su cuenta. ",
      "Paso 2:",
      "Vaya al sitio web ToolInsta, pegue el enlace de Instagram que acaba de copiar en el cuadro de entrada y presione el botón Descargar.",
      "Paso 3:",
      "Elija la calidad del video, luego comenzará la descarga.",
    ],
    how_to_download_story_heading: ["¿CÓMO DESCARGAR HISTORIAS DE INSTAGRAM?"],
    how_to_download_story_content: [
      "Para descargar fotos o videos de Instagram, debes seguir estos tres sencillos pasos.",
      "Paso 1:",
      "Abra la aplicación o el sitio web de Instagram e inicie sesión en su cuenta. ",
      "Paso 2:",
      "Vaya al sitio web ToolInsta, pegue el enlace de Instagram que acaba de copiar en el cuadro de entrada y presione el botón Descargar.",
      "Paso 3:",
      "Elija la calidad del video, luego comenzará la descarga.",
    ],
    why_choose_tootlinsta_heading: [
      "¿Por qué elegir ToolInsta para la MEJOR HERRAMIENTA DE DESCARGA DE INSTAGRAM?",
    ],
    why_choose_tootlinsta_content: [
      "Toolinsta es el mejor sitio web de terceros para descargar Instagram.",
      "Interfaz amigable",
      "Un buen descargador de Instagram debe tener una interfaz fácil de usar que sea fácil de navegar. ",
      "Velocidad de Descarga",
      "El sitio web puede descargar su contenido deseado de Instagram rápidamente, y no debería tomar mucho tiempo. Puede descargar más rápido en nuestro sitio web.",
      "Seguridad",
      "El sitio web es seguro y protegido, sin riesgo de virus o malware. ",
    ],
    faq_heading: ["Preguntas más frecuentes"],
    faq_content: [
      "¿Qué es el descargador de Instagram?",
      "Un descargador de Instagram es una herramienta que le permite descargar fotos, videos, carretes, historias y otro contenido de Instagram a su computadora o dispositivo móvil. ",
      "¿Puedo guardar videos directamente en Instagram?",
      "Sí, puede guardar videos directamente en Instagram, pero solo si el video es de su propia cuenta. ",
      "¿Cómo descargar videos y fotos en Instagram?",
      "Vaya a un sitio web de descarga de Instagram como ToolInsta, luego pegue la URL de la publicación de Instagram en el cuadro de entrada y presione el botón Descargar.",
      "¿Cómo descargar fotos y videos de Instagram en un teléfono Android?",
      "Descargue cualquier aplicación de descarga de Instagram de terceros y vaya a su cuenta de Instagram. ",
      "¿Hay algún límite en la cantidad de videos que puedo descargar?",
      "No hay límite. ",
      "¿Puedo descargar Instagram Story?",
      "Sí, puedes descargar. ",
      "¿Tengo que pagar por este video de descarga de Instagram?",
      "El servicio Toolinsta es completamente gratuito y no tiene límites de descarga.",
      "¿Dónde se guardan los videos y fotos de Instagram después de descargarlos?",
      'Consulte la carpeta "Descargas" en su teléfono o la sección "Historial de descargas" de su navegador.',
      "¿Cuál es la calidad más alta de imágenes y videos que puedo descargar?",
      "La calidad de las fotos y videos depende de la imagen original cargada. ",
    ],
  },
  de: {
    input_placeholder_text: "Fügen Sie die Instagram-URL ein",
    top_heading: "Downloader für Instagram",
    top_subheading:
      "Laden Sie Instagram-Videos, Reels, Fotos und Storys herunter",
    video_heading: "Instagram-Video-Downloader",
    video_subheading:
      "Laden Sie Instagram-Videos herunter, indem Sie die URL direkt einfügen",
    reel_heading: "Instagram-Rollen-Downloader",
    reel_subheading:
      "Laden Sie Instagram Reels herunter, indem Sie die URL direkt einfügen",
    story_heading: "Herunterladen von Instagram-Geschichten",
    story_subheading:
      "Laden Sie Instagram Stories herunter, indem Sie die URL direkt einfügen",
    photo_heading: "Downloader für Instagram-Fotos",
    photo_subheading:
      "Laden Sie Instagram-Fotos herunter, indem Sie die URL direkt einfügen",
    igtv_heading: "Instagram IGTV-Downloader",
    igtv_subheading:
      "Laden Sie Instagram IGTV-Videos herunter, indem Sie die URL direkt einfügen",
    home_desc_heading: ["Instagram Video, Reels, Foto, Story-Download"],
    home_desc_content: [
      "Laden Sie Instagram-Posts einfach mit ToolInsta herunter. ",
    ],
    video_desc_heading: ["Herunterladen von Instagram-Videos "],
    video_desc_content: [
      "Laden Sie Instagram-Videos einfach mit ToolInsta herunter. ",
    ],
    photo_desc_heading: ["Instagram-Foto herunterladen"],
    photo_desc_content: [
      "Laden Sie Instagram-Fotos einfach mit ToolInsta herunter. ",
    ],
    reel_desc_heading: ["Laden Sie Instagram-Rollen herunter"],
    reel_desc_content: [
      "Laden Sie Instagram Reels einfach mit ToolInsta herunter. ",
    ],
    story_desc_heading: ["Laden Sie die Instagram-Story herunter"],
    story_desc_content: [
      "Laden Sie Instagram Story einfach mit ToolInsta herunter. ",
    ],
    igtv_desc_heading: ["Instagram IGTV-Video herunterladen"],
    igtv_desc_content: [
      "Laden Sie Instagram-IGTV-Videos einfach mit ToolInsta herunter. ",
    ],
    about_heading: [
      "Downloader für Instagram: Laden Sie Instagram-Videos, Reels, Fotos und Storys herunter",
    ],
    about_content: [
      "Toolinsta ist ein Online-Tool oder eine Software, mit der Benutzer in wenigen einfachen Schritten Videos, Fotos, Stories, Reels und IGTV von Instagram herunterladen können. ",
      "Toolinsta ist so konzipiert, dass es auf jedem Gerät (PC, Mac, Android, iOS) einfach zu verwenden ist, ohne dass unterstützende Software installiert werden muss. ",
      "Die Nutzung unserer Website ist kostenlos und Sie können so viele Videos, Fotos und Geschichten herunterladen, wie Sie möchten. ",
    ],
    about_video_heading: [
      "Instagram zum Video-Download",
      "Instagram-Video-Downloader",
      "Instagram-Video-Downloader für das iPhone",
      "Speichern Sie Videos von Instagram",
    ],
    about_video_content: [
      "Wir bekommen viele solcher Videos in Instagram, die wir herunterladen möchten. ",
      "Eine Instagram-Video-Downloader-Website ist eine Plattform, die es Benutzern ermöglicht, Videos von Instagram auf ihre Geräte herunterzuladen.  ",
      "Es gibt mehrere Möglichkeiten, Instagram-Videos auf ein iPhone herunterzuladen, einschließlich der Verwendung einer Drittanbieter-App oder eines webbasierten Dienstes. ",
      "Das Speichern von Videos auf Instagram ist sehr einfach. ",
    ],
    about_reel_heading: [
      "Laden Sie Instagram To Reels herunter",
      "Instagram-Rollen-Downloader",
      "Instagram Reels Downloader für das iPhone",
      "Rollen von Instagram speichern",
    ],
    about_reel_content: [
      "Wir bekommen viele solcher Reels in Instagram, die wir herunterladen möchten. ",
      "Eine Instagram Reels Downloader-Website ist eine Plattform, die es Benutzern ermöglicht, Videos von Instagram auf ihre Geräte herunterzuladen.  ",
      "Es gibt mehrere Möglichkeiten, Instagram Reels auf ein iPhone herunterzuladen, einschließlich der Verwendung einer Drittanbieter-App oder eines webbasierten Dienstes. ",
      "Das Speichern von Reels auf Instagram ist sehr einfach. ",
    ],
    about_story_heading: [
      "Laden Sie Instagram zu Story herunter",
      "Instagram Story-Downloader",
      "Instagram Story-Downloader für das iPhone",
      "Speichern Sie die Geschichte von Instagram",
    ],
    about_story_content: [
      "Wir bekommen viele solcher Fotos in Instagram, die wir herunterladen möchten. ",
      "Eine Instagram-Foto-Downloader-Website ist eine Plattform, die es Benutzern ermöglicht, Videos von Instagram auf ihre Geräte herunterzuladen.  ",
      "Es gibt mehrere Möglichkeiten, Instagram-Geschichten auf ein iPhone herunterzuladen, einschließlich der Verwendung einer Drittanbieter-App oder eines webbasierten Dienstes. ",
      "Das Speichern von Fotos auf Instagram ist sehr einfach. ",
    ],
    about_photo_heading: [
      "Instagram zum Foto-Download",
      "Instagram-Foto-Downloader",
      "Instagram-Foto-Downloader für das iPhone",
      "Foto von Instagram speichern",
    ],
    about_photo_content: [
      "Wir bekommen viele solcher igtv in Instagram, die wir herunterladen möchten. ",
      "Eine Instagram igtv Downloader-Website ist eine Plattform, die es Benutzern ermöglicht, Videos von Instagram auf ihre Geräte herunterzuladen.  ",
      "Es gibt mehrere Möglichkeiten, Instagram igtv auf ein iPhone herunterzuladen, einschließlich der Verwendung einer Drittanbieter-App oder eines webbasierten Dienstes. ",
      "Das Speichern von Fotos auf Instagram ist sehr einfach. ",
    ],
    about_igtv_heading: [
      "Laden Sie Instagram zu IGTV herunter",
      "Instagram IGTV-Downloader",
      "Instagram IGTV-Downloader für das iPhone",
      "Speichern Sie IGTV von Instagram",
    ],
    about_igtv_content: [
      "Wir bekommen viele solcher Geschichten in Instagram, die wir herunterladen möchten. ",
      "Eine Instagram Stories Downloader-Website ist eine Plattform, die es Benutzern ermöglicht, Videos von Instagram auf ihre Geräte herunterzuladen.  ",
      "Es gibt mehrere Möglichkeiten, Instagram-Geschichten auf ein iPhone herunterzuladen, einschließlich der Verwendung einer Drittanbieter-App oder eines webbasierten Dienstes. ",
      "Das Speichern von Stories auf Instagram ist sehr einfach. ",
    ],
    why_toolinsta_heading: [
      "Warum sollten Sie ToolInsta - Instagram Downloader verwenden?",
    ],
    why_toolinsta_content: [
      "Was ist Instagram: Instagram ist eine beliebte Social-Media-Plattform, die es Benutzern ermöglicht, Fotos, Videos, Filmrollen und Geschichten mit ihren Followern zu teilen. ",
      "Jeden Tag werden Millionen neuer Fotos, Videos und Reels auf Instagram gepostet, aber Instagram erlaubt Benutzern nicht, Fotos und Videos herunterzuladen und auf Ihrem Gerät zu speichern. ",
    ],
    features_heading: ["Funktionen von ToolInsta"],
    features_content: [
      "Video herunterladen Instagram",
      "ToolInsta, mit dem Benutzer Videos von Instagram herunterladen können. ",
      "Foto-Downloader für Instagram",
      "Download-Dienst für Instagram-Fotos, bereitgestellt von ToolInsta. ",
      "Laden Sie Instagram-Rollen herunter",
      "ToolInsta bester Downloader zum Herunterladen von Instagram-Reel-Videos im MP4-Format auf allen Geräten (PC, Mac, Android, iOS).",
      "IGTV-Video herunterladen",
      "IGTV ist ein langes Video auf Instagram, ToolInsta unterstützt das Herunterladen von IGTV-Videos auf Ihr Gerät zur Speicherung oder Wiedergabe, wenn es offline ist. ",
      "Laden Sie die Instagram-Story herunter",
      "Das Toolinsta Instagram Story Download-Tool ermöglicht es Benutzern, Inhalte aus Instagram-Storys schnell herunterzuladen. ",
      "Instagram-Audio-Download",
      "Instagram Audio Download bezieht sich auf den Vorgang des Herunterladens von Audiodateien von Instagram. ",
    ],
    how_to_download_heading: [
      "WIE KANN ICH VIDEOS VON INSTAGRAM HERUNTERLADEN?",
    ],
    how_to_download_content: [
      "Um Fotos oder Videos von Instagram herunterzuladen, müssen Sie diese drei einfachen Schritte befolgen.",
      "Schritt 1:",
      "Öffnen Sie die Instagram-Anwendung oder -Website und melden Sie sich bei Ihrem Konto an. ",
      "Schritt 2:",
      "Gehen Sie zur Website ToolInsta, fügen Sie den gerade kopierten Instagram-Link in das Eingabefeld ein und klicken Sie auf die Schaltfläche Download.",
      "Schritt 3:",
      "Wählen Sie die Qualität des Videos, danach beginnt der Download.",
    ],
    how_to_download_video_heading: [
      "WIE KANN ICH VIDEOS VON INSTAGRAM HERUNTERLADEN?",
    ],
    how_to_download_video_content: [
      "Um Fotos oder Videos von Instagram herunterzuladen, müssen Sie diese drei einfachen Schritte befolgen.",
      "Schritt 1:",
      "Öffnen Sie die Instagram-Anwendung oder -Website und melden Sie sich bei Ihrem Konto an. ",
      "Schritt 2:",
      "Gehen Sie zur Website ToolInsta, fügen Sie den gerade kopierten Instagram-Link in das Eingabefeld ein und klicken Sie auf die Schaltfläche Download.",
      "Schritt 3:",
      "Wählen Sie die Qualität des Videos, danach beginnt der Download.",
    ],
    how_to_download_reel_heading: [
      "WIE KANN MAN REELS VON INSTAGRAM HERUNTERLADEN?",
    ],
    how_to_download_reel_content: [
      "Um Fotos oder Videos von Instagram herunterzuladen, müssen Sie diese drei einfachen Schritte befolgen.",
      "Schritt 1:",
      "Öffnen Sie die Instagram-Anwendung oder -Website und melden Sie sich bei Ihrem Konto an. ",
      "Schritt 2:",
      "Gehen Sie zur Website ToolInsta, fügen Sie den gerade kopierten Instagram-Link in das Eingabefeld ein und klicken Sie auf die Schaltfläche Download.",
      "Schritt 3:",
      "Wählen Sie die Qualität des Videos, danach beginnt der Download.",
    ],
    how_to_download_photo_heading: [
      "WIE KANN MAN FOTOS VON INSTAGRAM HERUNTERLADEN?",
    ],
    how_to_download_photo_content: [
      "Um Fotos von Instagram herunterzuladen, müssen Sie diese drei einfachen Schritte befolgen.",
      "Schritt 1:",
      "Öffnen Sie die Instagram-Anwendung oder -Website und melden Sie sich bei Ihrem Konto an. ",
      "Schritt 2:",
      "Gehen Sie zur Website ToolInsta, fügen Sie den gerade kopierten Instagram-Link in das Eingabefeld ein und klicken Sie auf die Schaltfläche Download.",
      "Schritt 3:",
      "Wählen Sie die Qualität des Videos, danach beginnt der Download.",
    ],
    how_to_download_igtv_heading: [
      "WIE KANN ICH IGTV-VIDEOS VON INSTAGRAM HERUNTERLADEN?",
    ],
    how_to_download_igtv_content: [
      "Um igtv-Videos von Instagram herunterzuladen, müssen Sie diese drei einfachen Schritte befolgen.",
      "Schritt 1:",
      "Öffnen Sie die Instagram-Anwendung oder -Website und melden Sie sich bei Ihrem Konto an. ",
      "Schritt 2:",
      "Gehen Sie zur Website ToolInsta, fügen Sie den gerade kopierten Instagram-Link in das Eingabefeld ein und klicken Sie auf die Schaltfläche Download.",
      "Schritt 3:",
      "Wählen Sie die Qualität des Videos, danach beginnt der Download.",
    ],
    how_to_download_story_heading: [
      "WIE KANN ICH GESCHICHTEN VON INSTAGRAM HERUNTERLADEN?",
    ],
    how_to_download_story_content: [
      "Um Fotos oder Videos von Instagram herunterzuladen, müssen Sie diese drei einfachen Schritte befolgen.",
      "Schritt 1:",
      "Öffnen Sie die Instagram-Anwendung oder -Website und melden Sie sich bei Ihrem Konto an. ",
      "Schritt 2:",
      "Gehen Sie zur Website ToolInsta, fügen Sie den gerade kopierten Instagram-Link in das Eingabefeld ein und klicken Sie auf die Schaltfläche Download.",
      "Schritt 3:",
      "Wählen Sie die Qualität des Videos, danach beginnt der Download.",
    ],
    why_choose_tootlinsta_heading: [
      "Warum ToolInsta für den BESTEN TOOL INSTAGRAM DOWNLOADER wählen",
    ],
    why_choose_tootlinsta_content: [
      "Toolinsta ist die beste Drittanbieter-Website für Instagram-Downloader.",
      "Benutzerfreundliches Bedienfeld",
      "Ein guter Instagram-Downloader sollte eine benutzerfreundliche Oberfläche haben, die einfach zu navigieren ist. ",
      "Download-Geschwindigkeit",
      "Die Website ist in der Lage, Ihre gewünschten Inhalte schnell von Instagram herunterzuladen, und es sollte nicht zu viel Zeit in Anspruch nehmen. Sie können am schnellsten auf unserer Website herunterladen.",
      "Sicherheit",
      "Die Website ist sicher und geschützt, ohne Risiko von Viren oder Malware. ",
    ],
    faq_heading: ["FAQ"],
    faq_content: [
      "Was ist der Instagram-Downloader?",
      "Ein Instagram-Downloader ist ein Tool, mit dem Sie Fotos, Videos, Reels, Storys und andere Inhalte von Instagram auf Ihren Computer oder Ihr Mobilgerät herunterladen können. ",
      "Kann ich Videos direkt auf Instagram speichern?",
      "Ja, Sie können Videos direkt auf Instagram speichern, aber nur, wenn das Video von Ihrem eigenen Konto stammt. ",
      "Wie lade ich Videos und Fotos auf Instagram herunter?",
      "Gehen Sie zu einer Instagram-Downloader-Website wie ToolInsta, fügen Sie dann die Instagram-Post-URL in das Eingabefeld ein und klicken Sie auf die Schaltfläche Download.",
      "Wie lade ich Instagram-Fotos und -Videos auf ein Android-Handy herunter?",
      "Laden Sie eine Instagram-Downloader-App eines Drittanbieters herunter und gehen Sie zu Ihrem Instagram-Konto. ",
      "Gibt es Beschränkungen für die Anzahl der Videos, die ich herunterladen kann?",
      "Es gibt keine Grenzen. ",
      "Kann ich Instagram Story herunterladen?",
      "Ja, Sie können herunterladen. ",
      "Muss ich für dieses Download-Instagram-Video bezahlen?",
      "Der Toolinsta-Service ist völlig kostenlos und hat keine Download-Limits.",
      "Wo werden Instagram-Videos und -Fotos nach dem Herunterladen gespeichert?",
      'Bitte überprüfen Sie den Ordner "Downloads" auf Ihrem Telefon oder den Abschnitt "Download-Verlauf" Ihres Browsers.',
      "Was ist die höchste Qualität von Bildern und Videos, die ich herunterladen kann?",
      "Die Qualität von Fotos und Videos hängt vom ursprünglich hochgeladenen Bild ab. ",
    ],
  },
  hi: {
    input_placeholder_text: "इंस्टाग्राम URL पेस्ट करें",
    top_heading: "इंस्टाग्राम के लिए डाउनलोडर",
    top_subheading: "डाउनलोड करें इंस्टाग्राम वीडियो, रील्स, फोटो और स्टोरी",
    video_heading: "इंस्टाग्राम वीडियो डाउनलोडर",
    video_subheading: "सीधे यूआरएल पेस्ट करके इंस्टाग्राम वीडियो डाउनलोड करें",
    reel_heading: "इंस्टाग्राम रील्स डाउनलोडर",
    reel_subheading: "सीधे यूआरएल पेस्ट करके इंस्टाग्राम रील्स डाउनलोड करें",
    story_heading: "इंस्टाग्राम स्टोरीज डाउनलोडर",
    story_subheading: "सीधे यूआरएल पेस्ट करके इंस्टाग्राम स्टोरीज डाउनलोड करें",
    photo_heading: "इंस्टाग्राम तस्वीरें डाउनलोडर",
    photo_subheading: "सीधे यूआरएल पेस्ट करके इंस्टाग्राम फोटोज डाउनलोड करें",
    igtv_heading: "इंस्टाग्राम आईजीटीवी डाउनलोडर",
    igtv_subheading: "सीधे Url चिपका कर Instagram IGTV वीडियो डाउनलोड करें",
    home_desc_heading: ["इंस्टाग्राम वीडियो, रील्स, फोटो, स्टोरी डाउनलोड"],
    home_desc_content: [
      "टूलइंस्टा के साथ इंस्टाग्राम पोस्ट को आसानी से डाउनलोड करें। ",
    ],
    video_desc_heading: ["इंस्टाग्राम वीडियो डाउनलोड "],
    video_desc_content: [
      "ToolInsta के साथ आसानी से Instagram वीडियो डाउनलोड करें। ",
    ],
    photo_desc_heading: ["इंस्टाग्राम फोटो डाउनलोड"],
    photo_desc_content: [
      "टूलइंस्टा के साथ आसानी से इंस्टाग्राम फोटो डाउनलोड करें। ",
    ],
    reel_desc_heading: ["इंस्टाग्राम रील्स डाउनलोड करें"],
    reel_desc_content: [
      "ToolInsta के साथ instagram Reels को आसानी से डाउनलोड करें। ",
    ],
    story_desc_heading: ["इंस्टाग्राम स्टोरी डाउनलोड"],
    story_desc_content: [
      "टूलइंस्टा के साथ आसानी से इंस्टाग्राम स्टोरी डाउनलोड करें। ",
    ],
    igtv_desc_heading: ["इंस्टाग्राम IGTV वीडियो डाउनलोड"],
    igtv_desc_content: [
      "ToolInsta के साथ आसानी से Instagram igtv वीडियो डाउनलोड करें। ",
    ],
    about_heading: [
      "इंस्टाग्राम के लिए डाउनलोडर : इंस्टाग्राम वीडियो, रील्स, फोटो और स्टोरी डाउनलोड करें",
    ],
    about_content: [
      "Toolinsta एक ऑनलाइन टूल या सॉफ्टवेयर है जो उपयोगकर्ताओं को कुछ सरल चरणों में Instagram से वीडियो, फोटो, कहानियां, रील और IGTV डाउनलोड करने की अनुमति देता है। ",
      "Toolinsta को सहायक सॉफ़्टवेयर इंस्टॉल किए बिना किसी भी डिवाइस (PC, Mac, Android, iOS) पर उपयोग में आसान बनाने के लिए डिज़ाइन किया गया है। ",
      "हमारी वेबसाइट उपयोग करने के लिए स्वतंत्र है, और आप जितने चाहें उतने वीडियो, फोटो, कहानियां डाउनलोड कर सकते हैं। ",
    ],
    about_video_heading: [
      "इंस्टाग्राम टू वीडियो डाउनलोड",
      "इंस्टाग्राम वीडियो डाउनलोडर",
      "इंस्टाग्राम वीडियो डाउनलोडर आईफोन",
      "Instagram से वीडियो सहेजें",
    ],
    about_video_content: [
      "इंस्टाग्राम में हमें कई ऐसे वीडियो मिल जाते हैं, जिन्हें हम डाउनलोड करना चाहते हैं। ",
      "एक Instagram वीडियो डाउनलोडर वेबसाइट एक ऐसा प्लेटफ़ॉर्म है जो उपयोगकर्ताओं को अपने डिवाइस पर Instagram से वीडियो डाउनलोड करने की अनुमति देता है।  ",
      "आईफोन पर इंस्टाग्राम वीडियो डाउनलोड करने के कई तरीके हैं, जिसमें थर्ड-पार्टी ऐप या वेब-आधारित सेवा का उपयोग करना शामिल है। ",
      "इंस्टाग्राम पर वीडियो सेव करना बहुत आसान है। ",
    ],
    about_reel_heading: [
      "इंस्टाग्राम टू रील्स डाउनलोड करें",
      "इंस्टाग्राम रील्स डाउनलोडर",
      "इंस्टाग्राम रील्स डाउनलोडर आईफोन",
      "इंस्टाग्राम से रीलों को बचाएं",
    ],
    about_reel_content: [
      "Instagram में हमें बहुत से ऐसे Reels मिल जाते हैं जिन्हें हम Download करना चाहते हैं. ",
      "एक इंस्टाग्राम रील्स डाउनलोडर वेबसाइट एक ऐसा प्लेटफॉर्म है जो उपयोगकर्ताओं को अपने डिवाइस पर इंस्टाग्राम से वीडियो डाउनलोड करने की अनुमति देता है।  ",
      "किसी iPhone पर Instagram Reels को डाउनलोड करने के कई तरीके हैं, जिनमें तृतीय-पक्ष ऐप या वेब-आधारित सेवा का उपयोग करना शामिल है। ",
      "इंस्टाग्राम पर रील्स को सेव करना बहुत आसान है। ",
    ],
    about_story_heading: [
      "इंस्टाग्राम टू स्टोरी डाउनलोड",
      "इंस्टाग्राम स्टोरी डाउनलोडर",
      "इंस्टाग्राम स्टोरी डाउनलोडर आईफोन",
      "इंस्टाग्राम से स्टोरी सेव करें",
    ],
    about_story_content: [
      "इंस्टाग्राम में हमें कई ऐसी फोटोज मिल जाती हैं, जिन्हें हम डाउनलोड करना चाहते हैं। ",
      "एक इंस्टाग्राम फोटो डाउनलोडर वेबसाइट एक ऐसा प्लेटफॉर्म है जो उपयोगकर्ताओं को अपने डिवाइस पर इंस्टाग्राम से वीडियो डाउनलोड करने की अनुमति देता है।  ",
      "किसी iPhone पर Instagram कहानियों को डाउनलोड करने के कई तरीके हैं, जिनमें तृतीय-पक्ष ऐप या वेब-आधारित सेवा का उपयोग करना शामिल है। ",
      "इंस्टाग्राम पर फोटो सेव करना बहुत आसान है। ",
    ],
    about_photo_heading: [
      "फोटो डाउनलोड करने के लिए Instagram",
      "इंस्टाग्राम फोटो डाउनलोडर",
      "इंस्टाग्राम फोटो डाउनलोडर आईफोन",
      "इंस्टाग्राम से फोटो सेव करें",
    ],
    about_photo_content: [
      "हमें Instagram में बहुत से ऐसे igtv मिल जाते हैं जिन्हें हम डाउनलोड करना चाहते हैं. ",
      "एक Instagram igtv डाउनलोडर वेबसाइट एक ऐसा प्लेटफ़ॉर्म है जो उपयोगकर्ताओं को अपने डिवाइस पर Instagram से वीडियो डाउनलोड करने की अनुमति देता है।  ",
      "किसी iPhone पर Instagram igtv डाउनलोड करने के कई तरीके हैं, जिनमें तृतीय-पक्ष ऐप या वेब-आधारित सेवा का उपयोग करना शामिल है। ",
      "इंस्टाग्राम पर फोटो सेव करना बहुत आसान है। ",
    ],
    about_igtv_heading: [
      "इंस्टाग्राम से IGTV डाउनलोड करें",
      "इंस्टाग्राम आईजीटीवी डाउनलोडर",
      "इंस्टाग्राम आईजीटीवी डाउनलोडर आईफोन",
      "इंस्टाग्राम से IGTV को सेव करें",
    ],
    about_igtv_content: [
      "हमें इंस्टाग्राम में ऐसी कई कहानियां मिलती हैं, जिन्हें हम डाउनलोड करना चाहते हैं। ",
      "इंस्टाग्राम स्टोरीज़ डाउनलोडर वेबसाइट एक ऐसा प्लेटफ़ॉर्म है जो उपयोगकर्ताओं को अपने डिवाइस पर इंस्टाग्राम से वीडियो डाउनलोड करने की अनुमति देता है।  ",
      "किसी iPhone पर Instagram कहानियों को डाउनलोड करने के कई तरीके हैं, जिनमें तृतीय-पक्ष ऐप या वेब-आधारित सेवा का उपयोग करना शामिल है। ",
      "इंस्टाग्राम पर स्टोरीज सेव करना बहुत आसान है। ",
    ],
    why_toolinsta_heading: [
      "आपको ToolInsta - Instagram डाउनलोडर का उपयोग क्यों करना चाहिए?",
    ],
    why_toolinsta_content: [
      "इंस्टाग्राम क्या है: इंस्टाग्राम एक लोकप्रिय सोशल मीडिया प्लेटफॉर्म है जो उपयोगकर्ताओं को अपने अनुयायियों के साथ फोटो, वीडियो, रील और कहानी साझा करने की अनुमति देता है। ",
      "इंस्टाग्राम पर हर दिन लाखों नए फोटो, वीडियो, रील्स पोस्ट किए जाते हैं, लेकिन इंस्टाग्राम यूजर्स को फोटो और वीडियो को आपके डिवाइस पर डाउनलोड और स्टोर करने की अनुमति नहीं देता है। ",
    ],
    features_heading: ["टूल इंस्टा की विशेषताएं"],
    features_content: [
      "वीडियो डाउनलोड करें इंस्टाग्राम",
      "टूलइंस्टा जो उपयोगकर्ताओं को इंस्टाग्राम से वीडियो डाउनलोड करने की अनुमति देता है। ",
      "इंस्टाग्राम फोटो डाउनलोडर",
      "टूलइंस्टा द्वारा प्रदान की गई इंस्टाग्राम फोटो डाउनलोडर सेवा। ",
      "इंस्टाग्राम रील्स डाउनलोड करें",
      "सभी उपकरणों (पीसी, मैक, एंड्रॉइड, आईओएस) पर mp4 प्रारूप में इंस्टाग्राम रील वीडियो डाउनलोड करने के लिए टूलइंस्टा सर्वश्रेष्ठ डाउनलोडर।",
      "आईजीटीवी वीडियो डाउनलोड करें",
      "IGTV Instagram पर एक लंबा वीडियो है, ToolInsta ऑफ़लाइन होने पर स्टोरेज या प्लेबैक के लिए आपके डिवाइस पर IGTV वीडियो डाउनलोड करने का समर्थन करता है। ",
      "इंस्टाग्राम स्टोरी डाउनलोड",
      "टूलिनस्टा इंस्टाग्राम स्टोरी डाउनलोड टूल उपयोगकर्ताओं को इंस्टाग्राम कहानियों से सामग्री को जल्दी से डाउनलोड करने की अनुमति देता है। ",
      "इंस्टाग्राम ऑडियो डाउनलोड",
      "इंस्टाग्राम ऑडियो डाउनलोड का तात्पर्य इंस्टाग्राम से ऑडियो फाइलों को डाउनलोड करने की प्रक्रिया से है। ",
    ],
    how_to_download_heading: ["इंस्टाग्राम से वीडियो कैसे डाउनलोड करें?"],
    how_to_download_content: [
      "इंस्टाग्राम से फोटो या वीडियो डाउनलोड करने के लिए आपको इन तीन आसान स्टेप्स को फॉलो करना होगा।",
      "स्टेप 1:",
      "Instagram एप्लिकेशन या वेबसाइट खोलें, और अपने खाते में लॉगिन करें। ",
      "चरण दो:",
      "वेबसाइट ToolInsta पर जाएं, आपके द्वारा कॉपी किए गए Instagram लिंक को इनपुट बॉक्स में पेस्ट करें और डाउनलोड बटन दबाएं।",
      "चरण 3:",
      "वीडियो की क्वालिटी चुनें, इसके बाद डाउनलोड शुरू हो जाएगा।",
    ],
    how_to_download_video_heading: ["इंस्टाग्राम से वीडियो कैसे डाउनलोड करें?"],
    how_to_download_video_content: [
      "इंस्टाग्राम से फोटो या वीडियो डाउनलोड करने के लिए आपको इन तीन आसान स्टेप्स को फॉलो करना होगा।",
      "स्टेप 1:",
      "Instagram एप्लिकेशन या वेबसाइट खोलें, और अपने खाते में लॉगिन करें। ",
      "चरण दो:",
      "वेबसाइट ToolInsta पर जाएं, आपके द्वारा कॉपी किए गए Instagram लिंक को इनपुट बॉक्स में पेस्ट करें और डाउनलोड बटन दबाएं।",
      "चरण 3:",
      "वीडियो की क्वालिटी चुनें, इसके बाद डाउनलोड शुरू हो जाएगा।",
    ],
    how_to_download_reel_heading: ["इंस्टाग्राम से रील्स कैसे डाउनलोड करें?"],
    how_to_download_reel_content: [
      "इंस्टाग्राम से फोटो या वीडियो डाउनलोड करने के लिए आपको इन तीन आसान स्टेप्स को फॉलो करना होगा।",
      "स्टेप 1:",
      "Instagram एप्लिकेशन या वेबसाइट खोलें, और अपने खाते में लॉगिन करें। ",
      "चरण दो:",
      "वेबसाइट ToolInsta पर जाएं, आपके द्वारा कॉपी किए गए Instagram लिंक को इनपुट बॉक्स में पेस्ट करें और डाउनलोड बटन दबाएं।",
      "चरण 3:",
      "वीडियो की क्वालिटी चुनें, इसके बाद डाउनलोड शुरू हो जाएगा।",
    ],
    how_to_download_photo_heading: ["इंस्टाग्राम से फोटो कैसे डाउनलोड करें?"],
    how_to_download_photo_content: [
      "इंस्टाग्राम से फोटो डाउनलोड करने के लिए आपको इन तीन आसान स्टेप्स को फॉलो करना होगा।",
      "स्टेप 1:",
      "Instagram एप्लिकेशन या वेबसाइट खोलें, और अपने खाते में लॉगिन करें। ",
      "चरण दो:",
      "वेबसाइट ToolInsta पर जाएं, आपके द्वारा कॉपी किए गए Instagram लिंक को इनपुट बॉक्स में पेस्ट करें और डाउनलोड बटन दबाएं।",
      "चरण 3:",
      "वीडियो की क्वालिटी चुनें, इसके बाद डाउनलोड शुरू हो जाएगा।",
    ],
    how_to_download_igtv_heading: [
      "इंस्टाग्राम से IGTV वीडियो कैसे डाउनलोड करें?",
    ],
    how_to_download_igtv_content: [
      "Instagram से igtv वीडियो डाउनलोड करने के लिए, आपको इन तीन आसान चरणों का पालन करना होगा।",
      "स्टेप 1:",
      "Instagram एप्लिकेशन या वेबसाइट खोलें, और अपने खाते में लॉगिन करें। ",
      "चरण दो:",
      "वेबसाइट ToolInsta पर जाएं, आपके द्वारा कॉपी किए गए Instagram लिंक को इनपुट बॉक्स में पेस्ट करें और डाउनलोड बटन दबाएं।",
      "चरण 3:",
      "वीडियो की क्वालिटी चुनें, इसके बाद डाउनलोड शुरू हो जाएगा।",
    ],
    how_to_download_story_heading: [
      "इंस्टाग्राम से स्टोरीज कैसे डाउनलोड करें?",
    ],
    how_to_download_story_content: [
      "इंस्टाग्राम से फोटो या वीडियो डाउनलोड करने के लिए आपको इन तीन आसान स्टेप्स को फॉलो करना होगा।",
      "स्टेप 1:",
      "Instagram एप्लिकेशन या वेबसाइट खोलें, और अपने खाते में लॉगिन करें। ",
      "चरण दो:",
      "वेबसाइट ToolInsta पर जाएं, आपके द्वारा कॉपी किए गए Instagram लिंक को इनपुट बॉक्स में पेस्ट करें और डाउनलोड बटन दबाएं।",
      "चरण 3:",
      "वीडियो की क्वालिटी चुनें, इसके बाद डाउनलोड शुरू हो जाएगा।",
    ],
    why_choose_tootlinsta_heading: [
      "सर्वश्रेष्ठ टूल इंस्टाग्राम डाउनलोडर के लिए टूलइंस्टा क्यों चुनें",
    ],
    why_choose_tootlinsta_content: [
      "Toolinsta सर्वश्रेष्ठ Instagram डाउनलोडर तृतीय पक्ष वेबसाइट है।",
      "उपभोक्ता - अनुकूल इंटरफ़ेस",
      "एक अच्छे इंस्टाग्राम डाउनलोडर में यूजर फ्रेंडली इंटरफेस होना चाहिए जो नेविगेट करने में आसान हो। ",
      "डाउनलोड की गति",
      "वेबसाइट आपकी वांछित सामग्री को Instagram से जल्दी से डाउनलोड करने में सक्षम है, और इसमें बहुत अधिक समय नहीं लगना चाहिए। आप हमारी वेबसाइट में सबसे तेज़ डाउनलोड कर सकते हैं।",
      "सुरक्षा",
      "वेबसाइट सुरक्षित और सुरक्षित है, जिसमें वायरस या मैलवेयर का कोई जोखिम नहीं है। ",
    ],
    faq_heading: ["सामान्य प्रश्न"],
    faq_content: [
      "इंस्टाग्राम डाउनलोडर क्या है?",
      "इंस्टाग्राम डाउनलोडर एक ऐसा टूल है जो आपको इंस्टाग्राम से फोटो, वीडियो, रील, कहानी और अन्य सामग्री को अपने कंप्यूटर या मोबाइल डिवाइस पर डाउनलोड करने की अनुमति देता है। ",
      "क्या मैं सीधे Instagram पर वीडियो सहेज सकता हूँ?",
      "हाँ, आप वीडियो को सीधे Instagram पर सहेज सकते हैं, लेकिन केवल तभी जब वीडियो आपके अपने खाते से हो। ",
      "इंस्टाग्राम पर वीडियो और फोटो कैसे डाउनलोड करें?",
      "टूलइंस्टा जैसी इंस्टाग्राम डाउनलोडर वेबसाइट पर जाएं, फिर इंस्टाग्राम पोस्ट यूआरएल को इनपुट बॉक्स में पेस्ट करें और डाउनलोड बटन दबाएं।",
      "एंड्रॉइड फोन पर इंस्टाग्राम फोटो और वीडियो कैसे डाउनलोड करें?",
      "किसी भी तीसरे पक्ष के इंस्टाग्राम डाउनलोडर ऐप को डाउनलोड करें और अपने इंस्टाग्राम अकाउंट पर जाएं। ",
      "क्या मेरे द्वारा डाउनलोड किए जा सकने वाले वीडियो की संख्या की कोई सीमा है?",
      "कोई सीमा नही है। ",
      "क्या मैं इंस्टाग्राम स्टोरी डाउनलोड कर सकता हूं?",
      "हाँ आप डाउनलोड कर सकते हैं। ",
      "क्या मुझे इस डाउनलोड इंस्टाग्राम वीडियो के लिए भुगतान करना होगा",
      "Toolinsta सेवा पूरी तरह से निःशुल्क है और इसकी कोई डाउनलोड सीमा नहीं है।",
      "डाउनलोड करने के बाद Instagram वीडियो और फ़ोटो कहाँ सहेजे जाते हैं?",
      'कृपया अपने फ़ोन में "डाउनलोड" फ़ोल्डर या अपने ब्राउज़र के "डाउनलोड इतिहास" अनुभाग की जाँच करें।',
      "मेरे द्वारा डाउनलोड की जा सकने वाली छवियों और वीडियो की उच्चतम गुणवत्ता क्या है?",
      "फ़ोटो और वीडियो की गुणवत्ता अपलोड की गई मूल छवि पर निर्भर करती है। ",
    ],
  },
  it: {
    input_placeholder_text: "Incolla l'URL di Instagram",
    top_heading: "Downloader per Instagram",
    top_subheading: "Scarica video, bobine, foto e storia di Instagram",
    video_heading: "Scarica video da Instagram",
    video_subheading:
      "Scarica i video di Instagram incollando direttamente l'URL",
    reel_heading: "Downloader di bobine di Instagram",
    reel_subheading: "Scarica Instagram Reels incollando direttamente l'URL",
    story_heading: "Downloader di storie di Instagram",
    story_subheading:
      "Scarica le storie di Instagram incollando direttamente l'URL",
    photo_heading: "Downloader di foto di Instagram",
    photo_subheading:
      "Scarica le foto di Instagram incollando direttamente l'URL",
    igtv_heading: "Downloader IGTV di Instagram",
    igtv_subheading:
      "Scarica i video IGTV di Instagram incollando direttamente l'URL",
    home_desc_heading: ["Download di video, bobine, foto, storie di Instagram"],
    home_desc_content: [
      "Scarica facilmente i post di Instagram con ToolInsta. ",
    ],
    video_desc_heading: ["Download di video da Instagram "],
    video_desc_content: [
      "Scarica facilmente i video di Instagram con ToolInsta. ",
    ],
    photo_desc_heading: ["Scarica foto Instagram"],
    photo_desc_content: [
      "Scarica facilmente la foto di Instagram con ToolInsta. ",
    ],
    reel_desc_heading: ["Scarica bobine di Instagram"],
    reel_desc_content: ["Scarica facilmente instagram Reels con ToolInsta. "],
    story_desc_heading: ["Scarica la storia di Instagram"],
    story_desc_content: ["Scarica facilmente Instagram Story con ToolInsta. "],
    igtv_desc_heading: ["Scarica il video IGTV di Instagram"],
    igtv_desc_content: [
      "Scarica facilmente i video di instagram igtv con ToolInsta. ",
    ],
    about_heading: [
      "Downloader per Instagram: scarica video, bobine, foto e storie di Instagram",
    ],
    about_content: [
      "Toolinsta è uno strumento o software online che consente agli utenti di scaricare video, foto, storie, bobine e IGTV da Instagram in pochi semplici passaggi. ",
      "Toolinsta è progettato per essere facile da usare su qualsiasi dispositivo (PC, Mac, Android, iOS) senza installare software di supporto. ",
      "Il nostro sito Web è gratuito e puoi scaricare tutti i video, le foto e le storie che desideri. ",
    ],
    about_video_heading: [
      "Download di video da Instagram",
      "Scarica video da Instagram",
      "Downloader di video da Instagram iphone",
      "Salva i video da Instagram",
    ],
    about_video_content: [
      "Riceviamo molti di questi video su Instagram, che vogliamo scaricare. ",
      "Un sito Web di downloader di video di Instagram è una piattaforma che consente agli utenti di scaricare video da Instagram sui propri dispositivi.  ",
      "Esistono diversi modi per scaricare i video di Instagram su un iPhone, incluso l'utilizzo di un'app di terze parti o un servizio basato sul Web. ",
      "Salvare i video su Instagram è molto semplice. ",
    ],
    about_reel_heading: [
      "Scarica Instagram su bobine",
      "Downloader di bobine di Instagram",
      "Downloader di bobine di Instagram iphone",
      "Salva bobine da Instagram",
    ],
    about_reel_content: [
      "Riceviamo molti di questi Reel su Instagram, che vogliamo scaricare. ",
      "Un sito Web di downloader di Instagram Reels è una piattaforma che consente agli utenti di scaricare video da Instagram sui propri dispositivi.  ",
      "Esistono diversi modi per scaricare Instagram Reels su un iPhone, incluso l'utilizzo di un'app di terze parti o un servizio basato sul Web. ",
      "Salvare Reels su Instagram è molto semplice. ",
    ],
    about_story_heading: [
      "Download da Instagram alla storia",
      "Downloader di storie di Instagram",
      "Downloader di storie di Instagram iphone",
      "Salva la storia da Instagram",
    ],
    about_story_content: [
      "Riceviamo molte di queste foto su Instagram, che vogliamo scaricare. ",
      "Un sito Web di downloader di foto di Instagram è una piattaforma che consente agli utenti di scaricare video da Instagram sui propri dispositivi.  ",
      "Esistono diversi modi per scaricare le storie di Instagram su un iPhone, incluso l'utilizzo di un'app di terze parti o un servizio basato sul Web. ",
      "Salvare le foto su Instagram è molto semplice. ",
    ],
    about_photo_heading: [
      "Download di foto da Instagram",
      "Scarica foto da Instagram",
      "Scaricare foto da instagram iphone",
      "Salva foto da Instagram",
    ],
    about_photo_content: [
      "Riceviamo molti di questi igtv su Instagram, che vogliamo scaricare. ",
      "Un sito Web di downloader di Instagram igtv è una piattaforma che consente agli utenti di scaricare video da Instagram sui propri dispositivi.  ",
      "Esistono diversi modi per scaricare Instagram igtv su un iPhone, incluso l'utilizzo di un'app di terze parti o un servizio basato sul Web. ",
      "Salvare le foto su Instagram è molto semplice. ",
    ],
    about_igtv_heading: [
      "Download da Instagram a IGTV",
      "Downloader IGTV di Instagram",
      "Downloader di Instagram IGTV iphone",
      "Salva IGTV da Instagram",
    ],
    about_igtv_content: [
      "Riceviamo molte di queste storie su Instagram, che vogliamo scaricare. ",
      "Un sito Web di downloader di storie di Instagram è una piattaforma che consente agli utenti di scaricare video da Instagram sui propri dispositivi.  ",
      "Esistono diversi modi per scaricare le storie di Instagram su un iPhone, incluso l'utilizzo di un'app di terze parti o un servizio basato sul Web. ",
      "Salvare storie su Instagram è molto semplice. ",
    ],
    why_toolinsta_heading: [
      "Perché dovresti usare ToolInsta - Instagram Downloader?",
    ],
    why_toolinsta_content: [
      "Che cos'è Instagram: Instagram è una popolare piattaforma di social media che consente agli utenti di condividere foto, video, bobine e storie con i propri follower. ",
      "Ogni giorno vengono pubblicati su Instagram milioni di nuove foto, video e bobine, ma Instagram non consente agli utenti di scaricare e archiviare foto e video sul proprio dispositivo. ",
    ],
    features_heading: ["Caratteristiche di ToolInsta"],
    features_content: [
      "Video scarica Instagram",
      "ToolInsta che consente agli utenti di scaricare video da Instagram. ",
      "Scarica foto da Instagram",
      "Servizio di downloader di foto di Instagram fornito da ToolInsta. ",
      "Scarica bobine di Instagram",
      "ToolInsta miglior downloader per scaricare video reel di Instagram in formato mp4 su tutti i dispositivi (PC, Mac, Android, iOS).",
      "Scarica video IGTV",
      "IGTV è un lungo video su Instagram, ToolInsta supporta il download di video IGTV sul tuo dispositivo per l'archiviazione o la riproduzione quando è offline. ",
      "Scarica la storia di Instagram",
      "Lo strumento di download di Toolinsta Instagram Story consente agli utenti di scaricare rapidamente i contenuti dalle storie di Instagram. ",
      "Download dell'audio di Instagram",
      "Instagram Audio Download si riferisce al processo di download di file audio da Instagram. ",
    ],
    how_to_download_heading: ["COME SCARICARE VIDEO DA INSTAGRAM?"],
    how_to_download_content: [
      "Per scaricare foto o video da Instagram, devi seguire questi tre semplici passaggi.",
      "Passo 1:",
      "Apri l'applicazione o il sito web di Instagram e accedi al tuo account. ",
      "Passo 2:",
      "Vai al sito Web ToolInsta, incolla il link Instagram che hai appena copiato nella casella di input e premi il pulsante Download.",
      "Passaggio 3:",
      "Scegli la qualità del video, dopodiché inizierà il download.",
    ],
    how_to_download_video_heading: ["COME SCARICARE VIDEO DA INSTAGRAM?"],
    how_to_download_video_content: [
      "Per scaricare foto o video da Instagram, devi seguire questi tre semplici passaggi.",
      "Passo 1:",
      "Apri l'applicazione o il sito web di Instagram e accedi al tuo account. ",
      "Passo 2:",
      "Vai al sito Web ToolInsta, incolla il link Instagram che hai appena copiato nella casella di input e premi il pulsante Download.",
      "Passaggio 3:",
      "Scegli la qualità del video, dopodiché inizierà il download.",
    ],
    how_to_download_reel_heading: ["COME SCARICARE I REEL DA INSTAGRAM?"],
    how_to_download_reel_content: [
      "Per scaricare foto o video da Instagram, devi seguire questi tre semplici passaggi.",
      "Passo 1:",
      "Apri l'applicazione o il sito web di Instagram e accedi al tuo account. ",
      "Passo 2:",
      "Vai al sito Web ToolInsta, incolla il link Instagram che hai appena copiato nella casella di input e premi il pulsante Download.",
      "Passaggio 3:",
      "Scegli la qualità del video, dopodiché inizierà il download.",
    ],
    how_to_download_photo_heading: ["COME SCARICARE FOTO DA INSTAGRAM?"],
    how_to_download_photo_content: [
      "Per scaricare foto da Instagram, devi seguire questi tre semplici passaggi.",
      "Passo 1:",
      "Apri l'applicazione o il sito web di Instagram e accedi al tuo account. ",
      "Passo 2:",
      "Vai al sito Web ToolInsta, incolla il link Instagram che hai appena copiato nella casella di input e premi il pulsante Download.",
      "Passaggio 3:",
      "Scegli la qualità del video, dopodiché inizierà il download.",
    ],
    how_to_download_igtv_heading: ["COME SCARICARE VIDEO IGTV DA INSTAGRAM?"],
    how_to_download_igtv_content: [
      "Per scaricare video igtv da Instagram, devi seguire questi tre semplici passaggi.",
      "Passo 1:",
      "Apri l'applicazione o il sito web di Instagram e accedi al tuo account. ",
      "Passo 2:",
      "Vai al sito Web ToolInsta, incolla il link Instagram che hai appena copiato nella casella di input e premi il pulsante Download.",
      "Passaggio 3:",
      "Scegli la qualità del video, dopodiché inizierà il download.",
    ],
    how_to_download_story_heading: ["COME SCARICARE STORIE DA INSTAGRAM?"],
    how_to_download_story_content: [
      "Per scaricare foto o video da Instagram, devi seguire questi tre semplici passaggi.",
      "Passo 1:",
      "Apri l'applicazione o il sito web di Instagram e accedi al tuo account. ",
      "Passo 2:",
      "Vai al sito Web ToolInsta, incolla il link Instagram che hai appena copiato nella casella di input e premi il pulsante Download.",
      "Passaggio 3:",
      "Scegli la qualità del video, dopodiché inizierà il download.",
    ],
    why_choose_tootlinsta_heading: [
      "Perché scegliere ToolInsta per il MIGLIOR DOWNLOADER DI INSTAGRAM PER STRUMENTI",
    ],
    why_choose_tootlinsta_content: [
      "Toolinsta è il miglior sito Web di terze parti per il download di Instagram.",
      "Interfaccia user-friendly",
      "Un buon downloader di Instagram dovrebbe avere un'interfaccia intuitiva e facile da navigare. ",
      "Velocità di download",
      "Il sito Web è in grado di scaricare rapidamente i contenuti desiderati da Instagram e non dovrebbe richiedere troppo tempo. Puoi scaricare il più veloce nel nostro sito Web.",
      "Sicurezza",
      "Il sito Web è sicuro e protetto, senza alcun rischio di virus o malware. ",
    ],
    faq_heading: ["FAQ"],
    faq_content: [
      "Cos'è Instagram Downloader?",
      "Un downloader di Instagram è uno strumento che ti consente di scaricare foto, video, bobine, storie e altri contenuti da Instagram sul tuo computer o dispositivo mobile. ",
      "Posso salvare i video direttamente su Instagram?",
      "Sì, puoi salvare i video direttamente su Instagram, ma solo se il video proviene dal tuo account. ",
      "Come scaricare video e foto su Instagram?",
      "Vai su un sito Web di downloader di Instagram come ToolInsta, quindi incolla l'URL del post di Instagram nella casella di input e premi il pulsante Download.",
      "Come scaricare foto e video di Instagram sul telefono Android?",
      "Scarica qualsiasi app per il download di Instagram di terze parti e accedi al tuo account Instagram. ",
      "Ci sono limiti al numero di video che posso scaricare?",
      "Non c'è limite. ",
      "Posso scaricare Instagram Story?",
      "Sì, puoi scaricare. ",
      "Devo pagare per questo download di video Instagram",
      "Il servizio Toolinsta è completamente gratuito e non ha limiti di download.",
      "Dove vengono salvati i video e le foto di Instagram dopo il download?",
      'Controlla la cartella "Download" nel tuo telefono o la sezione "Cronologia download" del tuo browser.',
      "Qual è la massima qualità di immagini e video che posso scaricare?",
      "La qualità delle foto e dei video dipende dall'immagine originale caricata. ",
    ],
  },
  // ...
};

export const getStringInLocalLanguage = (title) => {
  return messages[
    localStorage.getItem("toolinsta_language_selected")
      ? localStorage.getItem("toolinsta_language_selected")
      : "en"
  ][title];
};
